<!DOCTYPE HTML>
<html>
<head>
<title>Sources of Waste</title>
<?php include_once("files/script.php"); ?>
</head>
<body class="no-sidebar">
<div id="header">
  <div class="inner">
    <header>
      <h1><a href="index.php" id="logo">Waste Management</a></h1>
    </header>
  </div>
  <?php include_once("files/header.php"); ?>
</div>
<div class="wrapper style1">
  <div class="container">
    <div class="row">
      <div class="12u skel-cell-mainContent" id="content">
        <article id="main" class="special">
          <header>
            <h2><a href="https://en.wikipedia.org/wiki/Waste">Sources of Waste</a></h2>
            <span class="byline"> Human society produces some unwanted and discarded materials which are called wastes. </span> </header>
          <a href="#" class="image featured"><img src="images/pic25.png" alt=""></a>
		  <h3>1.	Municipal Sources of waste:</h3>
		  <br>
          <p> 
This includes trash or garbage from households, schools, offices, market places, restaurants and other public places.
They include everyday items like food debris, used plastic bags, soda cans and plastic water bottles, broken furniture, grass clippings, product packaging, broken home appliances and clothing.
 </p>
          <section>
            <header>
              <h3>2.	Medical/Clinical sources of waste:</h3>
            </header>
            <p> Medical/clinical wastes, normally refers to waste produced from health care facilities, such as hospitals, clinics, surgical theaters, veterinary hospitals and labs. They tend to be classified as hazard waste rather than general waste. </p>
            <p> Items in this group include surgical items, pharmaceuticals, blood, body parts, wound dressing materials, needles and syringes </p>
          </section>
          <section>
            <header>
              <h3>3.	Agricultural sources of waste:</h3>
            </header>
            <p>Typically, this is waste generated by agricultural activities. These include horticulture, fruit growing, seed growing, livestock breeding, market gardens and seedling nurseries.</p>
			<p>Waste items in this group include empty pesticide containers, old silage wrap, out of date medicines and wormers, used tires, surplus milk, cocoa pods and corn husks. </p>
          </section>
        </article>
      </div>
    </div>
    <hr>
    <div class="row">
      <article class="4u special"> <a href="#" class="image featured"><img src="images/pic26.jpg" alt=""></a>
        <header>
          <h3><a href="https://en.wikipedia.org/wiki/Waste">End-of-life Automobiles</a></h3>
        </header>
        <p> When cars are all old and not working again, where do they end up? Many people just leave them to rust in the fields, but there is a better way to deal with them. In many cities, these vehicles are sent to the plant, where all the removable parts are taken out for recycling. The rest is flattened up and shredded into peices for recycling. The last bits that cannot be used again is sent to a landfill. </p>
      </article>
      <article class="4u special"> <a href="#" class="image featured"><img src="images/pic27.png" alt=""></a>
        <header>
          <h3><a href="https://en.wikipedia.org/wiki/Waste">Industrial sources of waste</a></h3>
        </header>
        <p>Since the industrial revolution, the rise in the number of industries manufacturing glass, leather, textile, food, electronics, plastic and metal products has significantly contributed to waste production. Take a look at the things in your home, every item there was probably manufactured and possibly, waste was produced as a result. </p>
      </article>
      <article class="4u special"> <a href="#" class="image featured"><img src="images/pic28.jpg" alt=""></a>
        <header>
          <h3><a href="https://en.wikipedia.org/wiki/Waste">Construction/demolition sources of waste</a></h3>
        </header>
        <p> Construction waste is that resulting from the construction of roads and building. Sometimes old buildings and structures are pulled down (demolished) to make space for new ones. This is particularly common in old cities that are modernizing. This is called demolition waste.</p>
      </article>
    </div>
  </div>
</div>
<div id="footer">
  <?php include_once("files/footer.php"); ?>
</div>
</body>
</html>